# Site Settings
title:               The 512 Goons
tagline:             Gaming news and Let's Plays
description:
baseurl:            "" #"/512 Goons
url:                ""
github:
  url:               #"https://lenpaul.github.io/Lagrange"
author:
  name:              "Gabe"
  email:             "csstrickster2@gmail.com"
  twitter:           "King_Gabes"
  instagram:         "KingGabes"
  github:            "CodingGabe"
  facebook:          "Kinggabes"
  linkedin:          "gabeamaya"
navigation:
- title: About
  url: /about
- title: Videos
  url: /videos
- title: Reviews
  url: /reviews

paginate:            5
disqus:              #"your-disqus"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
